baseURL = 'https://polarweasel.org/'
languageCode = 'en-ca'
title = "Alex Ball"
# theme = ["github.com/theNewDynamic/gohugo-theme-ananke/v2"]
theme = ["github.com/McShelby/hugo-theme-relearn"]

defaultContentLanguage = "en"
sectionPagesMenu = "main"
enableRobotsTXT = true

[sitemap]
changefreq = "monthly"
priority = 0.5
filename = "sitemap.xml"

[params]

author.name = "Teh Polarweasel"
collapsibleMenu=true
  # See here for a performance warning on collapsible menus:
  # https://mcshelby.github.io/hugo-theme-relearn/configuration/sidebar/menus/index.html#expander-for-submenus
