baseURL = 'https://polarweasel.org/gear/'
languageCode = 'en-ca'
title = "Polarweasel's sewing stuff"
theme = ["github.com/theNewDynamic/gohugo-theme-ananke/v2"]

resourceDir = "../resources"

defaultContentLanguage = "en"
sectionPagesMenu = "main"
enableRobotsTXT = true

[services.googleAnalytics]
id = ''

[pagination]
pagerSize = 3 # this is set low for demonstrating with dummy content. Set to a higher number

[languages.en]
contentDir = "content"
languageCode = 'en-CA'
weight = 1
title = "Polarweasel's sewing stuff"
# languageDirection = 'rtl' for Right-To-Left languages

# [languages.fr]
# contentDir = "content/fr"
# languageCode = 'fr-CA'
# weight = 2
# title = "Ananke Fr"

[sitemap]
changefreq = "monthly"
priority = 0.5
filename = "sitemap.xml"

[params]
text_color = ""
author = ""
favicon = ""
site_logo = ""
description = "The last theme you'll ever need. Maybe."
# choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
background_color_class = "bg-black"
# choose fitting and alignment styles for the featured image using Tachyons classes such as "cover|contain" for fitting and "bg-top|bg-center|bg-bottom" for alignment, or add any other class space-separated to customize further
featured_image_class = "cover bg-top"
# choose a color dimming class for the page or site header from any on this page: https://tachyons.io/docs/themes/skins/, preface it with "bg-" and add the value such as "-X0" where X is in [1,9]
cover_dimming_class = "bg-black-60"
recent_posts_number = 3

[params.ananke.social.share]
networks = [
  "email",
  "mastodon",
  "linkedin"
]

[params.ananke.social.follow]
networks = [
  "mastodon",
  "github",
  "linkedin"
]

[params.ananke.social.mastodon]
username = "polarweasel@hachyderm.io"
profilelink = "https://hachyderm.io/@polarweasel#."

[params.ananke.social.linkedin]
username = "polarweasel"
profilelink = "https://linkedin.com/in/polarweasel"

[params.ananke.social.github]
username = "polarweasel"
