baseURL = 'https://polarweasel.org/new-site/'
languageCode = 'en-ca'
title = "Alex Ball"
# theme = ["github.com/theNewDynamic/gohugo-theme-ananke/v2"]
theme = ["github.com/McShelby/hugo-theme-relearn"]

defaultContentLanguage = "en"
sectionPagesMenu = "main"
enableRobotsTXT = true
ignoreLogs = ['warning-goldmark-raw-html']

[sitemap]
changefreq = "monthly"
priority = 0.5
filename = "sitemap.xml"

[params]
  [[params.themeVariant]]
    identifier = 'neon'
    name = 'Theme: Neon'

  [[params.themeVariant]]
    auto = ['zen-light', 'zen-dark']
    identifier = 'zen-auto'
    name = 'Theme: Zen (auto light/dark)'

  [[params.themeVariant]]
    identifier = 'zen-light'
    name = 'Theme: Zen (light)'

  [[params.themeVariant]]
    identifier = 'zen-dark'
    name = 'Theme: Zen (dark)'

 author.name = "Teh Polarweasel"

#collapsibleMenu = true
  # See here for a performance warning on collapsible menus:
  # https://mcshelby.github.io/hugo-theme-relearn/configuration/sidebar/menus/index.html#expander-for-submenus

#editURL = 'https://github.com/polarweasel/sewing/edit/hugo-setup/sewing-info/content/${FilePath}'
