# Run a Hugo build with every pull request for the main branch.
#
# Not thorough QA, but at least you'll know you're breaking the build.

name: CI

on:
  # Run when a pull request against main branch is opened or updated
  pull_request:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    name: Run Hugo build
    runs-on: ubuntu-latest
    steps:
      - name: 🛒 Checkout
        uses: actions/checkout@v4
      - name: ✨ Install Hugo
        # env:
        #   HUGO_VERSION: 0.140.2
        run: |
          mkdir ~/hugo
          cd ~/hugo
          curl -L "https://github.com/gohugoio/hugo/releases/download/v${{ vars.HUGO_VERSION }}/hugo_${{ vars.HUGO_VERSION }}_Linux-64bit.tar.gz" --output hugo.tar.gz
          tar -xvzf hugo.tar.gz
          sudo mv hugo /usr/local/bin
      - name: 🛠️ Build
        run: hugo -s sewing-info/
